# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27a5789600d80ecd361f7c1bfee94ce32123837a0637399a32ec416a38f0c82e245b01990f8800c235bf0d6eedad7a774341188bb232f7e08e444e4032996ad

test:
  secret_key_base: 651e2ecd65333aa8f65dc11af55f1aeea4e6651191bd455e6dd8ea27ba609fceca6cbe9f911097f707d8f8fbdfcffdbbd1b7fb9ef90fd847b94f5f341e318297

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
